dofile(minetest.get_modpath(minetest.get_current_modname()).."/longsofas.lua")
dofile(minetest.get_modpath(minetest.get_current_modname()).."/sofas.lua")
dofile(minetest.get_modpath(minetest.get_current_modname()).."/armchairs.lua")
dofile(minetest.get_modpath(minetest.get_current_modname()).."/coffeetable.lua")
dofile(minetest.get_modpath(minetest.get_current_modname()).."/endtable.lua")
